### ISSUE TITLE
Table of Content: Missing Links

### ISSUE THREAD

**Issue by 0n1cOn3** [cyberknight777/SpamProtection-rs#1]
Table of Content has missing links and forward you to localhost.

**Comment by PeroSar** [comment]
@0n1cOn3 oh

**Comment by 0n1cOn3** [comment]
Yup. Just that you can fix it :)

**Comment by PeroSar** [comment]
can't reproduce this issue

**Comment by cyberknight777** [comment]
Seems to be an irreproducible issue for me too. Can you explain in detail at which part you're facing it?

**Comment by PeroSar** [comment]
@cyberknight777 seems like a problem on ios app only
